apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loadtests.example.org
spec:
  scope: Namespaced
  group: example.org
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: LoadTest
    plural: loadtests
    singular: loadtest
    shortNames:
      - ld
  additionalPrinterColumns:
    - name: Children
      type: string
      priority: 0
      JSONPath: .status.children
      description: The children pods created by the operator.
    - name: Result
      type: string
      priority: 0
      JSONPath: .status.result
      description: The result of this loadtest
    - name: State
      type: string
      priority: 0
      JSONPath: .status.state
      description: The state of the loadtest can be pending, executing or finished.