apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: simple.example.org
spec:
  scope: Namespaced
  group: example.org
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: SimpleDeployment
    plural: simpledeployments
    singular: simpledeployment
    shortNames:
      - simdep
      - sd
  additionalPrinterColumns:
    - name: Children
      type: string
      priority: 0
      JSONPath: .status.child
      description: The child pod created by the operator.